repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
      args:
        - --output-file README.md
